apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eidas-proxy
  description: eidas-proxy
  annotations:
    github.com/project-slug: felleslosninger/eidas-proxy
spec:
  type: application
  owner: team-idporten
  lifecycle: production
  system: eidas
  dependsOn:
    - resource:default/eidas-redis
    - component:eidas-idporten-proxy
