# Verifies PR title


name: PR Title Validation

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Pull Request Title
        id: validate-title
        uses: felleslosninger/github-actions/validate-pull-request-title@v1
        with:
          pull-request-title: ${{ github.event.pull_request.title }}
          allowed-prefixes: "Bump,ID-,MIN-,MP-,KRR-,PF-,AOS-,SP-,EIN-"
      - name: Print validation result
        run: echo "Is title valid? ${{ steps.validate-title.outputs.is-valid }}"
