# Verifies PR title


name: PR Title Validation

on:
  pull_request:
    branches: [ main ]
    types: [opened, edited]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Pull Request Title
        id: validate-title
        uses: felleslosninger/github-workflows/.github/workflows/ci-pr-checks.yml@main
        with:
          pull-request-title: ${{ github.event.pull_request.title }}
          pull-request-allowed-prefixes: "Bump,ID-,MIN-,MP-,KRR-,PF-,AOS-,SP-,EIN-"

