
name: Build Dockerfile

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: my-local-registery/eidas-proxy
      DOCKLE_HOST: "unix:///var/run/docker.sock"
    steps:
      - name: Set image tag
        id: set-image-tag
        run: |
          image_tag=$(date +'%Y-%m-%d-%H%M')-${GITHUB_SHA::8}
          echo "image-tag=$image_tag" >> "$GITHUB_OUTPUT"
          echo "- Image tag: $image_tag" >> "$GITHUB_STEP_SUMMARY"
      - uses: actions/checkout@v4
      - name: Build the tagged Docker image
        run: docker build --tag ${{ env.IMAGE_NAME}}:${{steps.set-image-tag.outputs.image-tag}} --file docker/Dockerfile --build-arg GIT_PACKAGE_TOKEN=${{secrets.GITHUB_TOKEN}} .
      - uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME}}:${{steps.set-image-tag.outputs.image-tag}}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2 # pin@v0.28.0
        id: trivy-primary
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db:2,public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db:1,public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: "${{ env.IMAGE_NAME}}:${{steps.set-image-tag.outputs.image-tag}}"
          exit-code: "1"
          severity: "CRITICAL,HIGH"